Malnutrition/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
]

core/urls.py
from django.urls import path
from .views import *

app_name ='core'

urlpatterns = [
    path('login/',login_page,name='login'),
    path("logout/",logout_page, name="logout"),
    path('index/',index,name='index'),
    path("index/stat/province", stat_province, name="stat_province"),
    path("index/stat/zone", stat_zone, name="stat_zone"),
    path("index/stat/aire", stat_aire, name="stat_aire"),
    path('index/province/list/',province_list,name='province_list'),
    path("index/provine/add/",province_create, name="province_create"),
    path("index/province/<int:pk>/update/", province_update, name="province_update"),
    path('index/zone-sanitaire/list/',zone_sanitaire_list,name='zone_sanitaire_list'),
    path("index/zone-sanitaire/add/", zone_sanitaire_create, name="zone_sanitaire_create"),
    path("index/zone-sanitaire/<int:pk>/update/", zone_sanitaire_update, name="zone_sanitaire_update"),
    path('index/aire-sanitaire/list/',aire_sanitaire_list,name='aire_sanitaire_list'),
    path("index/aire-sanitaire/add/", aire_sanitaire_create, name="aire_sanitaire_create"),
    path("index/aire-sanitaire/<int:pk>/update", aire_sanitaire_update, name="aire_sanitaire_update"),
    path("index/Enfant/add/", enfant_create, name="enfant_create"),
    path("index/Enfant/<int:pk>/Etat-initial/add/",etat_initial_create, name="etat_initial_create"),
    path("index/Enfant/<int:pk>/analyse-sanguine/add/",analyse_sanguine_create, name="analyse_sanguine_create"),
    path("index/Enfant/search/",enfant_search, name="enfant_search"),
    path("index/Enfant/<int:pk>/prelevement/list/",prelevement_list, name="prelevement_list"),
    path("index/Enfant/<int:pk>/prelevement/add/",prelevement_create, name="prelevement_create"),
    path("index/Enfant/<int:pk>/prelevement/<int:id>/delete/",prelevement_delete, name="prelevement_delete"),
    path("index/Enfant/<int:pk>/analyse-sanguine/list/",analyse_sanguine_list, name="analyse_sanguine_list"),
    path("index/Enfant/<int:pk>/analyse-sanguine/<int:id>/delete/",analyse_sanguine_delete, name="analyse_sanguine_delete"),
]

core/forms.py
from django import forms
from .models import *

class ProvinceForm(forms.ModelForm):
    class Meta:
        model = Province
        fields = ['nom_province']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nom_province'].widget.attrs.update({'class':'form-control',})

class ZoneSanitaireForm(forms.ModelForm):
    class Meta:
        model = ZoneSanitaire
        fields = ['nom_zone', 'address','code_province']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nom_zone'].widget.attrs.update({'class':'form-control',})
        self.fields['address'].widget.attrs.update({'class':'form-control',})
        self.fields['code_province'].widget.attrs.update({'class':'form-control',})

class AireSanitaireForm(forms.ModelForm):
    class Meta:
        model = AireSanitaire
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nom_aire'].widget.attrs.update({'class':'form-control',})
        self.fields['address'].widget.attrs.update({'class':'form-control',})
        self.fields['code_zone'].widget.attrs.update({'class':'form-control',})

class EnfantForm(forms.ModelForm):
    class Meta:
        model = Enfant
        fields = ['nom', 'postnom', 'prenom', 'sex', 'date_naissance', 'avenue', 'quartier', 'commune', 'ville','code_aire']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nom'].widget.attrs.update({'class':'form-control','placeholder':'Nom'})
        self.fields['prenom'].widget.attrs.update({'class':'form-control','placeholder':'Prenom'})
        self.fields['postnom'].widget.attrs.update({'class':'form-control','placeholder':'Postnom'})
        self.fields['sex'].widget.attrs.update({'class':'form-control','placeholder':'Prenom'})
        self.fields['date_naissance'].widget.attrs.update({'class':'form-control','placeholder':'Date naissance'})
        self.fields['avenue'].widget.attrs.update({'class':'form-control','placeholder':'Avenue'})
        self.fields['quartier'].widget.attrs.update({'class':'form-control','placeholder':'Quartier'})
        self.fields['commune'].widget.attrs.update({'class':'form-control','placeholder':'Commune'})
        self.fields['ville'].widget.attrs.update({'class':'form-control','placeholder':'Ville'})
        self.fields['code_aire'].widget.attrs.update({'class':'form-control','placeholder':'Aire Sanitaire'})


class PrelevementForm(forms.ModelForm):
    class Meta:
        model = Prelevement
        fields = [ 'poids', 'taille_en_cm', 'oedeme_nutri', 'classification','qte_spiruline_recue']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['poids'].widget.attrs.update({'class':'form-control','placeholder':'poids'})
        self.fields['taille_en_cm'].widget.attrs.update({'class':'form-control','placeholder':'taille_en_cm'})
        self.fields['oedeme_nutri'].widget.attrs.update({'class':'form-control','placeholder':'oedeme_nutri'})
        self.fields['classification'].widget.attrs.update({'class':'form-control','placeholder':'classification'})
        self.fields['qte_spiruline_recue'].widget.attrs.update({'class':'form-control','placeholder':'qte_spiruline_recue'})

class AnalyseSanguineForm(forms.ModelForm):
    class Meta:
        model = AnalyseSanguine
        fields = [ 'hemoglobine', 'albumine', 'azote_urique_sang', 'creatinine', 'uree_creatinine','fer_serique', 'ge']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['hemoglobine'].widget.attrs.update({'class':'form-control','placeholder':'hemoglobine'})
        self.fields['albumine'].widget.attrs.update({'class':'form-control','placeholder':'albumine'})
        self.fields['azote_urique_sang'].widget.attrs.update({'class':'form-control','placeholder':'azote_urique_sang'})
        self.fields['creatinine'].widget.attrs.update({'class':'form-control','placeholder':'creatinine'})
        self.fields['uree_creatinine'].widget.attrs.update({'class':'form-control','placeholder':'uree_creatinine'})
        self.fields['fer_serique'].widget.attrs.update({'class':'form-control','placeholder':'fer_serique'})
        self.fields['ge'].widget.attrs.update({'class':'form-control','placeholder':'ge'})

class EnfantSearchForm(forms.Form):
   name = forms.CharField(max_length=50, required=True)
   prenom = forms.CharField(max_length=40, required=True)
   postnom = forms.CharField(max_length=40,required=True)
   def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class':'form-control','placeholder':'name'})
        self.fields['prenom'].widget.attrs.update({'class':'form-control','placeholder':'prenom'})
        self.fields['postnom'].widget.attrs.update({'class':'form-control','placeholder':'postnom'})

core/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *
from django.contrib.auth import login,authenticate,logout
from django.conf import settings
from django.contrib.auth.decorators import login_required
from datetime import datetime,timedelta
date_actuelle = datetime.now().date()
deux_semaines= timedelta(weeks=2)


@login_required
def index(request):
    return render(request,'index.html')

@login_required
def stat_province(request):
    provinces = Province.objects.all()
    return render(request,'stat_province.html',{'provinces':provinces})


@login_required
def stat_zone(request):
    zone_sanitaires = ZoneSanitaire.objects.all()
    return render(request,'stat_zone.html',{'zone_sanitaires':zone_sanitaires})

@login_required
def stat_aire(request):
    aire_sanitaires = AireSanitaire.objects.all()
    return render(request,'stat_aire.html',{'aire_sanitaires':aire_sanitaires})

def login_page(request):
    if request.method=='POST':
        name=request.POST['username']
        pword=request.POST['password']
        user=authenticate(request,username=name,password=pword)
        if user is not  None:
            login(request,user )
            return redirect(settings.LOGIN_REDIRECT_URL)
        else:
            message='l\'email ou le mot de passe est incorrecte '
            return render(request,'login.html',{'message':message})
    return render(request,'login.html')

@login_required
def logout_page(request):
    logout(request)
    return redirect(settings.LOGIN_URL)

@login_required
def province_list(request):
    provinces = Province.objects.all()
    return render(request,'province_list.html',{'provinces':provinces})

@login_required
def zone_sanitaire_list(request): 
    zone_sanitaires = ZoneSanitaire.objects.all()
    return render(request,'zone_sanitaire_list.html',{'zone_sanitaires':zone_sanitaires,'view':'create'})

@login_required
def aire_sanitaire_list(request):
    aire_sanitaires = AireSanitaire.objects.all()
    return render(request,'aire_sanitaire_list.html',{'aire_sanitaires':aire_sanitaires})

@login_required
def province_create(request):
    view = 'Nouvelle'
    form = ProvinceForm()
    if request.method =="POST":
        form = ProvinceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:province_list')
    return render(request,'province_create.html',{'form':form,'view':view})

@login_required
def zone_sanitaire_create(request):
    view = 'Nouvelle'
    form = ZoneSanitaireForm()
    if request.method=="POST":
        form = ZoneSanitaireForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:zone_sanitaire_list')
    return render(request,'zone_sanitaire_create.html',{'form':form,'view':view})

@login_required
def aire_sanitaire_create(request):
    form = AireSanitaireForm()
    view = 'Nouvelle'
    if request.method == "POST":
        form = AireSanitaireForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:aire_sanitaire_list')
    return render(request,'aire_sanitaire_create.html',{'form':form,'view':view})

@login_required
def province_update(request, pk):
    view='Modifier'
    province = Province.objects.get(pk=pk)
    form = ProvinceForm(instance = province)
    if request.method == "POST":
        form = ProvinceForm(request.POST,instance = province)
        if form.is_valid():
            form.save()
        return redirect('core:province_list')
    return render(request,'province_create.html',{'form':form,'view':view})

@login_required
def zone_sanitaire_update(request, pk):
    view = 'Modifier'
    zone_sanitaire = ZoneSanitaire.objects.get(pk=pk)
    form = ZoneSanitaireForm(instance = zone_sanitaire)
    if request.method == "POST":
        form = ZoneSanitaireForm(request.POST,instance = zone_sanitaire)
        if form.is_valid():
            form.save()
        return redirect('core:zone_sanitaire_list')
    return render(request,'zone_sanitaire_create.html',{'form':form,'view':view})

@login_required
def aire_sanitaire_update(request, pk):
    view = 'Modifier'
    aire_sanitaire = AireSanitaire.objects.get(pk=pk)
    form = AireSanitaireForm(instance = aire_sanitaire)
    if request.method == "POST":
        form = AireSanitaireForm(request.POST,instance = aire_sanitaire)
        if form.is_valid():
            form.save()
        return redirect('core:aire_sanitaire_list')
    return render(request,'aire_sanitaire_create.html',{'form':form,'view':view})

def enfant_create(request):
    view='Entrer'
    form = EnfantForm()
    if request.method =="POST":
        form = EnfantForm(request.POST)
        if form.is_valid():
            enfant = form.save()
            context={
                'enfant':enfant
            }
            return render(request,'enfant_suite.html',context)
    return render(request,'enfant_create.html',{'form':form,'view':view})

def etat_initial_create(request,pk):
    view="Nouveau Prelevement"
    enfant = Enfant.objects.get(pk=pk)
    form = PrelevementForm()
    context={
        'form':form,
        'enfant':enfant,
        'view':view
    }
    if request.method=="POST":
        form = PrelevementForm(request.POST)
        if form.is_valid():
            prelevement= form.save(commit=False)

            #methode modele

            taille_en_cm = form.cleaned_data['taille_en_cm']
            taille_en_m= taille_en_cm/100
            poids = form.cleaned_data['poids']
            if enfant.age_en_annee > 0:
                pa= poids/enfant.age_en_annee
            else :
                pa= 1
            prelevement.code_id = enfant
            prelevement.code_aire = enfant.code_aire
            prelevement.taille_en_m = taille_en_m
            prelevement.pa = pa
            prelevement.save()
            EtatInital.objects.create(
                taille_en_m= taille_en_m,
                pa=pa,
                poids=prelevement.poids,
                taille_en_cm=prelevement.taille_en_cm,
                pb=prelevement.pb,
                oedeme_nutri=prelevement.oedeme_nutri,
                classification=prelevement.classification,
                code_id=enfant
            )
            context={
                'enfant':enfant,
                'prelevement':prelevement,
                'view':view
            }
            return render(request,'enfant_suite.html',context)
    return render(request,'prelevement_create.html',context)

def prelevement_create(request,pk):
    view="Nouveau Prelevement"
    enfant = Enfant.objects.get(pk=pk)
    form = PrelevementForm()
    prelevement_last= Prelevement.objects.filter(code_id=enfant).last()
    if prelevement_last:
        if date_actuelle - prelevement_last.date_prelevement >= deux_semaines:
            permis = True
        else :
            permis = False
    else :
        permis = True
    context={
        'form':form,
        'enfant':enfant,
        'view':view,
        'prelevement_last':prelevement_last,
        'permis':permis,
    }
    if request.method=="POST":
        form = PrelevementForm(request.POST)
        if form.is_valid():
            prelevement= form.save(commit=False)
             #methode modele

            taille_en_cm = form.cleaned_data['taille_en_cm']
            taille_en_m= taille_en_cm/100
            poids = form.cleaned_data['poids']
            if enfant.age_en_annee > 0:
                pa= poids/enfant.age_en_annee
            else :
                pa= 1
            prelevement.code_id = enfant
            prelevement.code_aire = enfant.code_aire
            prelevement.taille_en_m = taille_en_m
            prelevement.pa = pa
            prelevement.save()
            context={
                'enfant':enfant,
                'prelevement':prelevement,
                'view':view
            }
            return redirect('core:prelevement_list', enfant.code_id)
    return render(request,'prelevement_create.html',context)

def analyse_sanguine_create(request,pk):
    view ="Nouvelle analyse"
    enfant = Enfant.objects.get(pk=pk)
    form = AnalyseSanguineForm()
    analyse_sanguine_last = AnalyseSanguine.objects.filter(code_id = enfant).last()
    if analyse_sanguine_last:
        if date_actuelle.month > analyse_sanguine_last.date.month:
            if date_actuelle.day >= analyse_sanguine_last.date.day:
                permis=True
            else:
                permis= False
        else:
            permis=False
    else:
        permis=True
    context ={
        'form':form,
        'enfant':enfant,
        'view':view,
        'analyse_sanguine_last':analyse_sanguine_last,
        'permis':permis,
    }
    if request.method=="POST":
        form = AnalyseSanguineForm(request.POST)
        if form.is_valid():
            analyse_sanguine = form.save(commit=False)
            analyse_sanguine.code_id = enfant
            analyse_sanguine.code_aire = enfant.code_aire
            analyse_sanguine.save()
            context={
                'enfant':enfant,
                'analyse_sanguine':analyse_sanguine,
                'view':view,
            }
            return render(request,'enfant_suite.html',context)
    return render(request,'analyse_sanguine_create.html',context)

def enfant_search(request):
    form= EnfantSearchForm()
    context={
        'form':form
    }
    if request.method=="POST":
        form = EnfantSearchForm(request.POST)
        if form.is_valid():
            nom = form.cleaned_data['name']
            prenom = form.cleaned_data['prenom']
            postnom = form.cleaned_data['postnom']
            enfants = Enfant.objects.filter(nom=nom, prenom=prenom,postnom=postnom)
            context = {
                'enfants':enfants,
                'form':form,
            }
            return render(request,'enfant_search.html',context)
    return render(request,'enfant_search.html',context)

core/templates/aire_sanitaire_create.html
{% extends "index.html" %}
{% block title %}Formulaire{% endblock title %}
{% block content %}
<h2>{{view}} Aire sanitaire</h2>
<form method ='post'>
    {% csrf_token %}
    <div
        class="container"
    >
        <div
            class="row justify-content-center align-items-center g-2"
        >
            <div class="col ">
                <div class="form-floating mb-3">
                    {{form.nom_aire}}
                    <label for="{{form.nom_aire.id_for_label}}">Nom de l'aire sanitaire</label>
                </div>
            </div>
            <div class="col ">
                <div class="form-floating mb-3">
                    {{form.address}}
                    <label for="{{form.address.id_for_label}}">Adresse de l'aire sanitaire</label>
                </div>
            </div>
            <div class="col ">
                <div class="form-floating mb-3">
                    {{form.code_zone}}
                    <label for="{{form.code_zone.id_for_label}}">Sa zone Sanitaire </label>
                </div>
            </div>
            
        </div>
        
    </div>
    <div
        class="container"
    >
        <div
            class="row  "
        >
            <div class="d-flex   justify-content-center col">
                <button type="submit" class="btn btn-success">
                    Enregistrer
                </button>
            </div>
        
            <div class="d-flex justify-content-center col">
                <a
                    name=""
                    id=""
                    class="btn btn-secondary"
                    href="{%url 'core:aire_sanitaire_list'%}"
                    role="button"
                    >Annuler</a
                >

            </div>

        </div>

    </div>
</form>



{% endblock content %}

core/templates/aire_sanitaire_list.html
{% extends "index.html" %}
{% block title %}Listes des Aire sanitaire{% endblock title %}
{% block content %}
<div class="mb-2 container">
    <div
        class="row"
    >
        <div class="col-10"><h2>Listes des Aire sanitaire</h2></div>
        <div class="col-2">    
            <a href="{%url 'core:aire_sanitaire_create'%}" class=" btn btn-secondary  active" role="button" aria-pressed="true">Ajouter</a>
        </div>
        
    </div> 
</div>
<div class="table-responsive small">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nom</th>
        <th scope="col">Addresse</th>
        <th scope="col">Zone</th>
        <th scope="col">Action 1</th>
      </tr>
    </thead>
    <tbody>
        {% for aire_sanitaire in aire_sanitaires %}
        <tr>
            <td>{{aire_sanitaire.code_aire}}</td>
            <td>{{aire_sanitaire.nom_aire}}</td>
            <td>{{aire_sanitaire.address}}</td>
            <td>{{aire_sanitaire.code_zone}}</td>
            <td>
                <a class="mdf"href="{%url 'core:aire_sanitaire_update' aire_sanitaire.code_aire%}" style="color:rgb(30, 102, 209); text-decoration:none;">Modifier</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>


{% endblock content %}

core/templates/analyse_sanguine_list.html
{% extends "index.html" %}
{% block title %}Listes des Analyses sanguine{% endblock title %}
{% block content %}
<div class=" p-3 container">
  <div
      class="row"
  >
      <div class="col-10"><h2>Listes des Analyses sanguine concernant {{enfant.nom}} {{enfant.prenom}} {{enfant.postnom}} </h2></div>
      <div class="col">    
          <a href="{%url 'core:analyse_sanguine_create' enfant.code_id %}" class=" btn btn-primary  btn-sm p-2 active" role="button" aria-pressed="true">Nouvelle Analyse</a>
      </div>
      
  </div> 
</div>
<div class="table-responsive small">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">Numero</th>
        <th scope="col">Date </th>
        <th scope="col">hemoglobine</th>
        <th scope="col">Albumine</th>
        <th scope="col">Azote urique sang</th>
        <th scope="col">creatinine</th>
        <th scope="col">Uree creatinine</th>
        <th scope="col">fer serique</th>
        <th scope="col">ge</th>
        <th scope="col">Action 1</th>
      </tr>
    </thead>
    <tbody>
        {% for an in analyse_sanguines %}
        <tr>
            <td>{{an.id}}</td>
            <td>{{an.date}}</td>
            <td>{{an.hemoglobine}}</td>
            <td>{{an.albumine}}</td>
            <td>{{an.azote_urique_sang}}</td>
            <td>{{an.creatinine}}</td>
            <td>{{an.uree_creatinine}}</td>
            <td>{{an.fer_serique}}</td>
            <td>{{an.ge}}</td>
            <td>
                <a href="{%url 'core:analyse_sanguine_delete' enfant.code_id an.id %}" style="color:red; text-decoration:none;">Supprimer</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>


{% endblock content %}

core/templates/enfant_suite.html
{% extends "index.html" %}
{% block title %}Listes des Provinces{% endblock title %}
{% block content %}
<div class="mb-2 container">
  <div class="row">
      <div class="col-10"><h2>Informations Generale</h2></div> 
  </div> 
</div>
<div class="table-responsive small mb-3">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nom</th>
        <th scope="col">Prenom</th>
        <th scope="col">Postnom</th>
        <th scope="col">Sex</th>
        <th scope="col">Date de naissance</th>
        <th scope="col">villle</th>
        <th scope="col">Aire Sanitaire</th>
        <th scope="col">Commune</th>
        <th scope="col">Quartier</th>
        <th scope="col">Avenue</th>

      </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{enfant.code_id}}</td>
            <td>{{enfant.nom}}</td>
            <td>{{enfant.prenom}}</td>
            <td>{{enfant.postnom}}</td>
            <td>{{enfant.sex}}</td>
            <td>{{enfant.date_naissance}}</td>
            <td>{{enfant.ville}}</td>
            <td>{{enfant.code_aire}}</td>
            <td>{{enfant.commune}}</td>
            <td>{{enfant.quartier}}</td>
            <td>{{enfant.avenue}}</td>
        </tr>
    </tbody>
    {% if view == "Nouveau Prelevement" %}
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Quantite de spiruline</th>
        <th scope="col">Date de prelevement</th>
        <th scope="col">Poids</th>
        <th scope="col">Taille(m)</th>
        <th scope="col">Taille(cm)</th>
        <th scope="col">Imc</th>
        <th scope="col">Oedeme Nutritionelle</th>
        {% if prelevement.pb %}
        <th scope="col">Perimetre Brachial</th>
        {% endif %}
        <th scope="col">Poids pour age(p/a)</th>
        <th scope="col">Classification</th>
  
      </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{prelevement.numero}}</td>
            <td>{{prelevement.qte_spiruline_recue}}</td>
            <td>{{prelevement.date_prelevement}}</td>
            <td>{{prelevement.poids}}</td>
            <td>{{prelevement.taille_en_m}}</td>
            <td>{{prelevement.taille_en_cm}}</td>
            <td>{{prelevement.imc}}</td>
            <td>{{prelevement.oedeme_nutri}}</td>
            {% if prelevement.pb %}
            <td>{{prelevement.pb}}</td>
            {% endif %}
            <td>{{prelevement.pa}}</td>
            <td>{{prelevement.classification}}</td>
        </tr>
    </tbody>
    {% endif %}
    {% if view == "Nouvelle analyse" %}
    
    <thead >
      <tr>
        <th scope="col">ID</th>
        <th scope="col">hemoglobine</th>
        <th scope="col">Albumine</th>
        <th scope="col">Azote urique Sang </th>
        <th scope="col">Creatinine</th>
        <th scope="col">Uree creatinine</th>
        <th scope="col">fer serique</th>
        <th scope="col">ge</th>
  
      </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{analyse_sanguine.id}}</td>
            <td>{{analyse_sanguine.hemoglobine}}</td>
            <td>{{analyse_sanguine.albumine}}</td>
            <td>{{analyse_sanguine.azote_urique_sang}}</td>
            <td>{{analyse_sanguine.creatinine}}</td>
            <td>{{analyse_sanguine.uree_creatinine}}</td>
            <td>{{analyse_sanguine.fer_serique}}</td>
            <td>{{analyse_sanguine.ge}}</td>
        </tr>
    </tbody>
    {% endif %}
  </table>
</div>
<div class="container">
    <div class="row">
        <div class="col">
            <a class="btn btn-primary" href="{% url 'core:etat_initial_create' enfant.code_id %}" >Prelevement</a>   
        </div>
        <div class="col">
            <a class="btn btn-primary" href="{%url 'core:analyse_sanguine_create' enfant.code_id%}" >Analyse sanguine</a>      
        </div>
    </div>
</div>
{% endblock content %}

core/templates/province_list.html
{% extends "index.html" %}
{% block title %}Listes des Provinces{% endblock title %}
{% block content %}
<div class="mb-2 container">
  <div
      class="row"
  >
      <div class="col-10"><h2>Listes des Province</h2></div>
      <div class="col-2">    
          <a href="{%url 'core:province_create'%}" class=" btn btn-secondary  active" role="button" aria-pressed="true">Ajouter</a>
      </div>
      
  </div> 
</div>
<div class="table-responsive small">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nom</th>
        <th scope="col">Action 1</th>
      </tr>
    </thead>
    <tbody>
        {% for province in provinces %}
        <tr>
            <td>{{province.code_province}}</td>
            <td>{{province.nom_province}}</td>
            <td>
                <a href="{%url 'core:province_update' province.code_province%}" style="color:rgb(30, 102, 209); text-decoration:none;">Modifier</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>


{% endblock content %}